app/models.py
from app import db

class Car(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    modelo = db.Column(db.String(100))
    marca = db.Column(db.String(100))
    ano = db.Column(db.Integer)
    km = db.Column(db.Integer)
    cambio = db.Column(db.String(100))
    combustivel = db.Column(db.String(100))
    final_da_placa = db.Column(db.String(100))
    cor = db.Column(db.String(100))
    preco = db.Column(db.Float)
    image_url = db.Column(db.String(200))


    def __repr__(self):
        return f'<Car {self.name}>'

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from config import Config  # Importe a classe Config
import os

db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)  # Use a classe Config diretamente

    db.init_app(app)
    migrate.init_app(app, db)

    # Importar e registrar blueprints
    from app.routes.main_routes import main_bp
    from app.routes.auth_routes import auth_bp
    from app.routes.car_routes import car_bp

    app.register_blueprint(main_bp, url_prefix='/')
    app.register_blueprint(auth_bp, url_prefix='/auth')
    app.register_blueprint(car_bp, url_prefix='/cars')

    # Verificar se o diretório de imagens existe, se não, criar
    if not os.path.exists(app.config['UPLOAD_FOLDER']):
        os.makedirs(app.config['UPLOAD_FOLDER'])

    return app

app/routes/auth_routes.py
from flask import Blueprint, render_template, request, redirect, url_for

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['usuario']
        password = request.form['senha']

        if username == 'admin' and password == '12345':
            return redirect(url_for('car.dashboard'))
        else:
            return "Usuário ou senha inválidos", 401

    return render_template('login.html')

app/routes/car_routes.py
import os
from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app
from werkzeug.utils import secure_filename
from app.models import Car
from app import db

car_bp = Blueprint('car', __name__)

UPLOAD_FOLDER = os.path.join(os.getcwd(),'app', 'static','images')
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

def allowed_file(filename):
    """Verifica se o arquivo tem uma extensão permitida."""
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@car_bp.route('/dashboard')
def dashboard():
    cars = Car.query.all()
    return render_template('dashboard.html', cars=cars)

@car_bp.route('/estoque')
def estoque():
    cars = Car.query.all()
    return render_template('estoque.html', cars=cars)


@car_bp.route('/add_car', methods=['GET', 'POST'])
def add_car():
    if request.method == 'POST':
        # Obter os campos do formulário
        modelo = request.form.get('modelo')
        marca = request.form.get('marca')
        ano = request.form.get('ano')
        km = request.form.get('km')
        cambio = request.form.get('cambio')
        combustivel = request.form.get('combustivel')
        final_placa = request.form.get('final_placa')
        cor = request.form.get('cor')
        preco = request.form.get('preco')


        # Verificar se os campos obrigatórios foram preenchidos
        if not marca or not modelo or not preco or not ano or not km or not cambio or not combustivel or not final_placa or not cor:
            flash('Todos os campos são obrigatórios!')
            return redirect(request.url)

        # Verificar se o arquivo foi enviado
        if 'image' not in request.files:
            flash('Nenhuma imagem foi enviada!')
            return redirect(request.url)

        image = request.files['image']

        # Validar o arquivo
        if image.filename == '':
            flash('Nenhuma imagem selecionada!')
            return redirect(request.url)

        if not allowed_file(image.filename):
            flash('Formato de arquivo não permitido! Use PNG, JPG, JPEG ou GIF.')
            return redirect(request.url)

        # Salvar a imagem no diretório de uploads
        filename = secure_filename(image.filename)
        image_path = os.path.join(UPLOAD_FOLDER, filename)
        image.save(image_path)

        # Criar o novo carro e salvar no banco de dados
        new_car = Car(marca=marca, modelo=modelo, ano=ano, km=km, cambio=cambio, combustivel=combustivel, final_da_placa=final_placa, cor=cor, preco=preco, image_url=filename)
        db.session.add(new_car)
        db.session.commit()

        flash('Carro cadastrado com sucesso!')
        return redirect(url_for('car.dashboard'))

    return render_template('add_car.html')


@car_bp.route('/edit_car/<int:id>', methods=['GET', 'POST'])
def edit_car(id):
    car = Car.query.get(id)

    if request.method == 'POST':
        # Obter os dados do formulário
        modelo = request.form.get('modelo')
        marca = request.form.get('marca')
        ano = request.form.get('ano')
        km = request.form.get('km')
        cambio = request.form.get('cambio')
        combustivel = request.form.get('combustivel')
        final_placa = request.form.get('final_placa')
        cor = request.form.get('cor')
        preco = request.form.get('preco')

        # Verificar se uma nova imagem foi enviada
        if 'image' in request.files:
            image = request.files['image']
            if image.filename != '':
                if not allowed_file(image.filename):
                    flash('Formato de arquivo não permitido! Use PNG, JPG, JPEG ou GIF.')
                    return redirect(request.url)
                filename = secure_filename(image.filename)
                image_path = os.path.join(UPLOAD_FOLDER, filename)
                image.save(image_path)
                car.image_url = filename

        db.session.commit()
        flash('Carro atualizado com sucesso!')
        return redirect(url_for('car.dashboard'))

    return render_template('edit_car.html', car=car)


@car_bp.route('/delete_car/<int:id>', methods=['POST'])
def delete_car(id):
    car = Car.query.get(id)
    db.session.delete(car)
    db.session.commit()
    flash('Carro deletado com sucesso!')
    return redirect(url_for('car.dashboard'))

app/routes/main_routes.py
from flask import Blueprint, render_template
from app.models import Car

main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def landpage():
    carros = Car.query.all()
    return render_template('landpage.html', carros=carros)

app/templates/add_car.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adicionar Novo Carro</title>
    <!-- Adicionando o link do Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- CSS personalizado -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/carros.css') }}">
</head>
<body>

<div class="container">
    <h1>Adicionar Novo Carro</h1>

    <!-- Exibir mensagens de erro (flash) -->
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-warning" role="alert">
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    {% endwith %}

    <form method="POST" action="{{ url_for('car.add_car') }}" enctype="multipart/form-data">
        <div class="form-group">
            <label for="marca">Marca:</label>
            <input type="text" id="marca" name="marca" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="modelo">Modelo:</label>
            <input type="text" id="modelo" name="modelo" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="ano">Ano:</label>
            <input type="number" id="ano" name="ano" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="km">Quilometragem:</label>
            <input type="number" id="km" name="km" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="cambio">Câmbio:</label>
            <select id="cambio" name="cambio" class="form-control" required>
                <option value="manual">Manual</option>
                <option value="automatico">Automático</option>
                </select>
        </div>
        <div class="form-group">
            <label for="combustivel">Combustível:</label>
            <select id="combustivel" name="combustivel" class="form-control" required>
                <option value="gasolina">Gasolina</option>
                <option value="alcool">Álcool</option>
                <option value="flex">Flex</option>
                <option value="diesel">Diesel</option>
                </select>
        </div>
        <div class="form-group">
            <label for="final_placa">Final da Placa:</label>
            <input type="number" id="final_placa" name="final_placa" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="cor">Cor:</label>
            <select id="cor" name="cor" class="form-control" required>
                <option value="branco">Branco</option>
                <option value="preto">Preto</option>
                <option value="prata">Prata</option>
                <option value="azul">Azul</option>
                <option value="vermelho">Vermelho</option>
                <option value="verde">Verde</option>
                <option value="amarelo">Amarelo</option>
                <option value="laranja">Laranja</option>
                <option value="roxo">Roxo</option>
                <option value="rosa">Rosa</option>
                <option value="marrom">Marrom</option>
                <option value="cinza">Cinza</option>
                <option value="bege">Bege</option>
                <option value="dourado">Dourado</option>
                <option value="prata">Prata</option>
                <option value="grafite">Grafite</option>
                <option value="creme">Creme</option>
                <option value="outro">Outro</option>
            </select>
        </div>
        <div class="form-group">
            <label for="preco">Preço:</label>
            <input type="number" id="preco" name="preco" class="form-control" required step="0.01">
        </div>
        <div class="form-group">
            <label for="image">Imagem:</label>
            <input type="file" id="image" name="image" accept="image/*" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-primary">Adicionar Carro</button>
    </form>

    <a href="{{ url_for('car.dashboard') }}">Voltar ao Dashboard</a>
</div>

<!-- Scripts do Bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>

</body>
</html>

app/templates/dashboard.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard - Gerenciar Carros</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">
</head>
<body>
    <div class="container py-5">
        <!-- Header -->
        <header class="dashboard-header">
            <h1 class="h4">Dashboard - Gerenciar Carros</h1>
            <p class="text-muted">Adicione os veículos, edite-os e os exclua após a venda.</p>
        </header>

        <!-- Exibição de mensagens de flash -->
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="alert alert-warning" role="alert">
                    <ul>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        {% endwith %}

        <!-- Botão para adicionar carro -->
        <div class="text-end mb-4">
            <a href="{{ url_for('car.add_car') }}" class="btn btn-success">Adicionar Carro</a>
            <a href="{{ url_for('main.landpage') }}" class="btn btn-primary">Voltar ao site</a>
        </div>
        <!-- Lista de carros -->
        <div class="row">
            {% if cars %}
                {% for car in cars %}
                    <div class="col-md-4 mb-4">
                        <div class="card h-100">
                            <!-- Verificar se a imagem existe ou mostrar uma imagem padrão -->
                             <div class="card-img-container">
                                <img src="{{ url_for('static', filename='images/' + car.image_url) }}" class="card-img-top car-img-custom" alt="{{ car.name }}">
                            </div>
                            <div class="card-body">
                                <h5 class="card-title"><strong>{{ car.marca }}</strong> {{ car.modelo }}</h5>
                                <p class="card-text">
                                    <strong>Ano:</strong> {{ car.ano }}<br>
                                    <strong>Quilometragem:</strong> {{ car.km }} km<br>
                                    <strong>Câmbio:</strong> {{ car.cambio }}<br>
                                    <strong>Combustível:</strong> {{ car.combustivel }}<br>
                                    <strong>Preço:</strong> R$ {{ car.preco }}
                                </p>
                            </div>
                            <div class="card-footer d-flex justify-content-between">
                                <a href="{{ url_for('car.edit_car', id=car.id) }}" class="btn btn-warning btn-sm">Editar</a>
                                <form action="{{ url_for('car.delete_car', id=car.id) }}" method="POST" style="display:inline;">
                                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Tem certeza que deseja excluir este carro?')">
                                        Excluir
                                    </button>
                                </form>                                 
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="col-12">
                    <p class="text-center">Nenhum carro cadastrado.</p>
                </div>
            {% endif %}
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/templates/edit_car.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar carro</title>
    <!-- Adicionando o link do Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- CSS personalizado -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/carros.css') }}">
</head>
<body>

<div class="container">
    <h1>Editar {{car.modelo}} </h1>

    <!-- Exibir mensagens de erro (flash) -->
    {% with messages = get_flashed_messages() %}
        {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}
    {% endwith %}

    <form method="POST" action="{{ url_for('car.edit_car', id=car.id) }}" enctype="multipart/form-data">
        <div class="form-group">
            <label for="marca">Marca:</label>
            <input type="text" id="marca" name="marca" class="form-control" required value="{{car.marca}}">
        </div>
        <div class="form-group">
            <label for="modelo">Modelo:</label>
            <input type="text" id="modelo" name="modelo" class="form-control" required value="{{car.modelo}}">
        </div>
        <div class="form-group">
            <label for="ano">Ano:</label>
            <input type="number" id="ano" name="ano" class="form-control" required value="{{car.ano}}">
        </div>
        <div class="form-group">
            <label for="km">Quilometragem:</label>
            <input type="number" id="km" name="km" class="form-control" required value="{{car.km}}">
        </div>
        <div class="form-group">
            <label for="cambio">Câmbio:</label>
            <select id="cambio" name="cambio" class="form-control" required value="{{car.cambio}}">
                <option value="manual">Manual</option>
                <option value="automatico">Automático</option>
                </select>
        </div>
        <div class="form-group">
            <label for="combustivel">Combustível:</label>
            <select id="combustivel" name="combustivel" class="form-control" required value="{{car.combustivel}}">
                <option value="gasolina">Gasolina</option>
                <option value="alcool">Álcool</option>
                <option value="flex">Flex</option>
                <option value="diesel">Diesel</option>
            </select>
        </div>
        <div class="form-group">
            <label for="final_placa">Final da Placa:</label>
            <input type="number" id="final_placa" name="final_placa" class="form-control" required value="{{car.final_da_placa}}">
        </div>
        <div class="form-group">
            <label for="cor">Cor:</label>
            <select id="cor" name="cor" class="form-control" required value="{{car.cor}}">
                <option value="branco">Branco</option>
                <option value="preto">Preto</option>
                <option value="prata">Prata</option>
                <option value="azul">Azul</option>
                <option value="vermelho">Vermelho</option>
                <option value="verde">Verde</option>
                <option value="amarelo">Amarelo</option>
                <option value="laranja">Laranja</option>
                <option value="roxo">Roxo</option>
                <option value="rosa">Rosa</option>
                <option value="marrom">Marrom</option>
                <option value="cinza">Cinza</option>
                <option value="bege">Bege</option>
                <option value="dourado">Dourado</option>
                <option value="prata">Prata</option>
                <option value="grafite">Grafite</option>
                <option value="creme">Creme</option>
                <option value="outro">Outro</option>
            </select>
        </div>
        <div class="form-group">
            <label for="preco">Preço:</label>
            <input type="number" id="preco" name="preco" class="form-control" required step="0.01" value="{{car.preco}}">
        </div>
        <div class="form-group">
            <label for="image">Imagem:</label>
            <input type="file" id="image" name="image" accept="image/*" class="form-control" >
        </div>
        <button type="submit" class="btn btn-primary">Salvar carro</button>
    </form>

    <a href="{{ url_for('car.dashboard') }}">Voltar ao Dashboard</a>
</div>

<!-- Scripts do Bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>

</body>
</html>

app/templates/estoque.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Estoque de carros </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">
</head>
<body>
    <!-- Header -->
    <header class="bg-dark text-white py-3">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark">
               <!-- <img src="{{ url_for('static', filename='images/') }}" alt="Ronconi Car's" width="50" padding-right="w-100"> -->
                <a class="navbar-brand h4" href="#">Garagem atual</a>
                <!-- Botão do menu mobile -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Itens do menu -->
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a href="{{ url_for('main.landpage')}}" class="nav-link text-white">HOME</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <div class="row">
        {% if cars %}
            {% for car in cars %}
                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        <!-- Verificar se a imagem existe ou mostrar uma imagem padrão -->
                         <div class="card-img-container">
                            <img src="{{ url_for('static', filename='images/' + car.image_url) }}" class="card-img-top car-img-custom" alt="{{ car.name }}">
                        </div>
                        <div class="card-body">
                            <h5 class="card-title"><strong>{{ car.marca }}</strong> {{ car.modelo }}</h5>
                            <p class="card-text">
                                <strong>Ano:</strong> {{ car.ano }}<br>
                                <strong>Quilometragem:</strong> {{ car.km }} km<br>
                                <strong>Câmbio:</strong> {{ car.cambio }}<br>
                                <strong>Combustível:</strong> {{ car.combustivel }}<br>
                                <strong>Preço:</strong> R$ {{ car.preco }}
                            </p>
                        </div>
                        <div class="card-footer d-flex justify-content-between">
                            <a href="{{ url_for('car.edit_car', id=car.id) }}" class="btn btn-warning btn-sm">Editar</a>
                            <form action="{{ url_for('car.delete_car', id=car.id) }}" method="POST" style="display:inline;">
                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Tem certeza que deseja excluir este carro?')">
                                    Excluir
                                </button>
                            </form>                                 
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="col-12">
                <p class="text-center">Nenhum carro no estoque.</p>
            </div>
        {% endif %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/templates/landpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Loja de Carros</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/landpage.css') }}">

</head>
<body >
    <!-- Header -->
    <header class="bg-dark text-white py-3">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark">
               <!-- <img src="{{ url_for('static', filename='images/') }}" alt="Ronconi Car's" width="50" padding-right="w-100"> -->
                <a class="navbar-brand h4" href="#">Ronconi Garage</a>
                <!-- Botão do menu mobile -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Itens do menu -->
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a href="{{ url_for('car.estoque')}}" class="nav-link text-white">ESTOQUE</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url_for('auth.login') }}" class="nav-link text-white">LOGIN</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>

    <!-- Hero Section -->
    <section class="hero">
        <h1>Encontre o carro dos seus sonhos!</h1>
        <p>Os melhores veículos seminovos com qualidade e garantia.</p>
        <a href="{{ url_for('car.estoque')}}" class="btn btn-primary">Confira o Estoque</a>
    </section>

    <!-- Carrossel de Carros -->
    <section id="estoque" class="py-5 bg-black text-white mb-4">
        <div class="container">
            <h2 class="text-center mb-4">Garagem atual</h2>
            <div id="carrosCarousel" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    {% for carro in carros %}
                    <div class="carousel-item {% if loop.index == 1 %}active{% endif %}">
                        <div class="row justify-content-center">
                            <div class="col-md-6 text-center">
                                <img src="{{ url_for('static', filename='images/' + carro.image_url) }}" class="d-block responsive-img" alt="{{ carro.model }}">
                                <h3 class="mt-3">{{ carro.marca }} {{ carro.modelo }} </h3>
                                <strong>Ano:</strong> {{ carro.ano }}<br>
                                <strong>Quilometragem:</strong> {{ carro.km }} km<br>
                                <strong>Câmbio:</strong> {{ carro.cambio }}<br>
                                <strong>Combustível:</strong> {{ carro.combustivel }}<br><br>
                                <a href="#" class="btn btn-primary">Mais Detalhes</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carrosCarousel" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Anterior</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carrosCarousel" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Próximo</span>
                </button>
            </div>
        </div>
    </section>

    <!-- Contato -->
    <section id="informacao" class="text-center mt-5">
        <div class="container">
            <div class="row align-items-center">
                <!-- Texto à esquerda -->
                <div class="col-md-6">
                    <h2>Entre em Contato Conosco!</h2>
                    <p class="text-start">Meu nome é Jorge Ronconi e sou garageiro a mais de 15 anos, trabalho com a revenda de carros e consultoria na compra e avaliação de carros.</p>
                    <a href="#" class="btn btn-primary">Me mande uma mensagem</a>
                </div>
                
                <!-- Imagem à direita -->
                <div class="col-md-6">
                    <img src="{{ url_for('static', filename='images/image.png') }}" alt="Imagem de contato" class="img-fluid responsive-img-contat">
                </div>
            </div>
        </div>
    </section>
    <script src="script.js"></script>
    <!-- Footer -->
    <footer class="bg-dark text-white py-3 mt-5">
        <p>&copy; 2025 Loja de Carros. Todos os direitos reservados.</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login - Loja de Carros</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
</head>
<body>
    <div class="login-container">
        <div class="login-header">
            <h1 class="h4">Login</h1>
            <p class="text-muted">Acesse sua conta para gerenciar os veículos</p>
        </div>
        <form method="POST" action="{{ url_for('auth.login') }}">
            <div class="mb-3">
                <label for="usuario" class="form-label">Usuário</label>
                <input type="text" class="form-control" id="usuario" name="usuario" placeholder="Digite seu usuário" required>
            </div>
            <div class="mb-3">
                <label for="senha" class="form-label">Senha</label>
                <input type="password" class="form-control" id="senha" name="senha" placeholder="Digite sua senha" required>
            </div>
            <button type="submit" class="btn btn-primary w-100">Entrar</button>
        </form>
        <div class="text-end mb-4">
            <a href="{{ url_for('main.landpage') }}" class="btn btn-danger w-100 mt-2">Cancelar</a>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>